version: "3.8"

services:
  praxis-ui-prod:
    build:
      context: ../../
      dockerfile: docker/praxis-ui-prod/Dockerfile
    container_name: praxis-ui-prod
    image: praxis-ui-prod
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "${PORT}:${PORT}"
