version: "3.8"

services:
  praxis-ui-dev:
    build:
      context: ../../
      dockerfile: docker/praxis-ui-dev/Dockerfile
    container_name: praxis-ui-dev
    image: praxis-ui-dev
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - ${PORT}:${PORT}
